stages:
  - build
  - test
  - deploy


.init_ssh:
  #TODO
  
.change_file_permissions: 
  #TODO
    
composer:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - cp .env.staging .env
      - php artisan key:generate
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - .env

npm:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
  script:
      - npm install
      - npm run production
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - public/css/
      - public/js/


phpunit:
  stage: test
  dependencies:
    - composer
  script:
    - phpunit --coverage-text --colors=never

staging:
  stage: deploy
  script:
    #- *init_ssh
    #- *change_file_permissions
    - php artisan deploy dev.devopsdemo.nic.in -s upload  #TODO: NOT CONFIRMED 
  environment:
    name: staging
    url: http://dev.devopsdemo.nic.in #this demo url must be configured as per actual url
  only:
    - master


#THIS STAGE WILL BE USED LATER FOR FINAL DEPLOYMENT
production:
  stage: deploy
  script:
    #- *init_ssh
    #- *change_file_permissions
    - php artisan deploy devopsdemo.nic.in -s upload  #TODO: NOT CONFIRMED 
  environment:
    name: production
    url: http://devopsdemo.nic.in   #this demo url must be configured as per actual url
  when: manual
  only:
   - master